# The CI for each commit, prints envs and content of GITHUB_EVENT_PATH
name: Debug

'on':
  [pull_request, pull_request_review, release, workflow_dispatch, workflow_call]

jobs:
  DebugInfo:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@a701ed95a46e6f2fb0df25e1a558c16356fae35a
  TestEphemeral:
    runs-on: [self-hosted, builder]
    strategy:
      matrix:
        versions: [0, 1, 2]
    steps:
    - uses: hmarr/debug-action@a701ed95a46e6f2fb0df25e1a558c16356fae35a
